/* Generated by scripts/project-facts.ts. Do not edit. */
export const projectFacts = {
  methodology:
    'This page counts physical lines in source files. It leaves out dependencies, build output, dist, and generated reference images.',
  totals: {
    sourceLines: 25439,
    sourceFiles: 133,
    cFamilyLines: 19885,
    typescriptLines: 3700,
    documentationLines: 1513,
    referenceProgramLines: 4385,
    referenceOutputs: 4312,
  },
  areas: [
    {
      path: 'include/',
      label: 'Public C API',
      description: 'Defines the types and functions that hosts can call.',
      files: 8,
      lines: 1569,
    },
    {
      path: 'lib/',
      label: 'C implementation',
      description: 'Contains the parser, compiler, graph data, collections, and CPU renderer.',
      files: 28,
      lines: 9190,
    },
    {
      path: 'cli/',
      label: 'Command-line tool',
      description: 'Runs, inspects, renders, packages, and compares BinScript programs.',
      files: 7,
      lines: 1912,
    },
    {
      path: 'bindings/',
      label: 'Host bindings',
      description: 'Connects the C library to JavaScript through a small WebAssembly ABI.',
      files: 3,
      lines: 1939,
    },
    {
      path: 'apps/',
      label: 'Browser app',
      description: 'Contains this React site, the CodeMirror editor, and the compact generated-set example.',
      files: 20,
      lines: 2391,
    },
    {
      path: 'integrations/',
      label: 'Platform adapters',
      description: 'Copies rendered output into Godot resources and Wii GX textures.',
      files: 23,
      lines: 3177,
    },
    {
      path: 'tests/',
      label: 'Tests',
      description: 'Covers the native library, BinScript language, WebAssembly build, fuzz targets, and host integrations.',
      files: 27,
      lines: 3832,
    },
    {
      path: 'scripts/',
      label: 'Build scripts',
      description: 'Generates files, stages the Wasm runtime, checks the reference inventory, and runs benchmarks.',
      files: 12,
      lines: 1202,
    },
  ],
  semanticFiles: [
    {
      path: 'lib/semantic/program_assets.c',
      lines: 402,
    },
    {
      path: 'lib/semantic/program_collections.c',
      lines: 305,
    },
    {
      path: 'lib/semantic/program_compile.c',
      lines: 477,
    },
    {
      path: 'lib/semantic/program_core.c',
      lines: 525,
    },
    {
      path: 'lib/semantic/program_evaluate.c',
      lines: 192,
    },
    {
      path: 'lib/semantic/program_gradients.c',
      lines: 362,
    },
    {
      path: 'lib/semantic/program_internal.h',
      lines: 257,
    },
    {
      path: 'lib/semantic/program_members.c',
      lines: 804,
    },
    {
      path: 'lib/semantic/program_runtime.c',
      lines: 239,
    },
  ],
} as const;
