set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR powerpc)

if(NOT DEFINED ENV{DEVKITPPC})
  message(FATAL_ERROR "DEVKITPPC must point to the devkitPPC toolchain root")
endif()

set(CMAKE_C_COMPILER "$ENV{DEVKITPPC}/bin/powerpc-eabi-gcc")
set(CMAKE_CXX_COMPILER "$ENV{DEVKITPPC}/bin/powerpc-eabi-g++")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(BB_BUILD_CLI OFF CACHE BOOL "" FORCE)
set(BB_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(BB_BUILD_WASM OFF CACHE BOOL "" FORCE)
set(BB_BUILD_WII ON CACHE BOOL "" FORCE)
