import { readFile, writeFile } from 'node:fs/promises';

import {
  gradientExampleSource,
  layeredExampleSource,
  maskExampleSource,
  overviewExampleSource,
} from '../apps/browser/binscript-examples.js';
import { highlightBinScript } from './binscript-highlighter.js';

const outputPath = new URL('../apps/browser/binscript-highlight.generated.ts', import.meta.url);
const generated = `/* Generated by scripts/highlight-binscript.ts. Do not edit. */
// prettier-ignore
export const overviewExampleHtml = ${JSON.stringify(highlightBinScript(overviewExampleSource))};
// prettier-ignore
export const gradientExampleHtml = ${JSON.stringify(highlightBinScript(gradientExampleSource))};
// prettier-ignore
export const maskExampleHtml = ${JSON.stringify(highlightBinScript(maskExampleSource))};
// prettier-ignore
export const layeredExampleHtml = ${JSON.stringify(highlightBinScript(layeredExampleSource))};
`;

if (process.argv.includes('--check')) {
  const current = await readFile(outputPath, 'utf8').catch(() => '');
  if (current !== generated) {
    console.error('BinScript highlighting is stale. Run npm run highlight:binscript.');
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, generated);
  console.log('Generated apps/browser/binscript-highlight.generated.ts');
}
