import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { extname } from 'node:path';
import { format } from 'oxfmt';

const destination = 'apps/browser/project-facts.generated.ts';
const checkOnly = process.argv.includes('--check');
const excludedPrefixes = ['.build/', 'dist/', 'node_modules/', 'reference-set/'];
const generatedFiles = new Set([destination]);
const sourceExtensions = new Set(['.c', '.h', '.cpp', '.hpp', '.ts', '.tsx', '.css', '.binscript', '.cmake']);
const countedExtensions = new Set([...sourceExtensions, '.md', '.yml', '.yaml']);

interface FileFact {
  path: string;
  lines: number;
}

function lineCount(text: string): number {
  if (text.length === 0) return 0;
  return text.endsWith('\n') ? text.split('\n').length - 1 : text.split('\n').length;
}

function isCounted(path: string): boolean {
  if (excludedPrefixes.some((prefix) => path.startsWith(prefix)) || generatedFiles.has(path)) return false;
  return countedExtensions.has(extname(path)) || path.endsWith('CMakeLists.txt') || path.endsWith('/Makefile');
}

function isSource(path: string): boolean {
  return sourceExtensions.has(extname(path)) || path.endsWith('CMakeLists.txt') || path.endsWith('/Makefile');
}

const paths = execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard', '-z'], {
  encoding: 'utf8',
})
  .split('\0')
  .filter((path) => path.length > 0 && existsSync(path) && isCounted(path))
  .sort();

const files: FileFact[] = [];
for (const path of paths) files.push({ path, lines: lineCount(await readFile(path, 'utf8')) });

const areaDefinitions = [
  ['include', 'Public C API', 'Defines the types and functions that hosts can call.'],
  ['lib', 'C implementation', 'Contains the parser, compiler, graph data, collections, and CPU renderer.'],
  ['cli', 'Command-line tool', 'Runs, inspects, renders, packages, and compares BinScript programs.'],
  ['bindings', 'Host bindings', 'Connects the C library to JavaScript through a small WebAssembly ABI.'],
  ['apps', 'Browser app', 'Contains this React site, the CodeMirror editor, and the compact generated-set example.'],
  ['integrations', 'Platform adapters', 'Copies rendered output into Godot resources and Wii GX textures.'],
  ['tests', 'Tests', 'Covers the native library, BinScript language, WebAssembly build, fuzz targets, and host integrations.'],
  ['scripts', 'Build scripts', 'Generates files, stages the Wasm runtime, checks the reference inventory, and runs benchmarks.'],
] as const;

const areas = areaDefinitions.map(([path, label, description]) => {
  const matching = files.filter((file) => file.path === path || file.path.startsWith(`${path}/`));
  return {
    path: `${path}/`,
    label,
    description,
    files: matching.length,
    lines: matching.reduce((total, file) => total + file.lines, 0),
  };
});

const implementationFiles = files.filter((file) => isSource(file.path));
const markdownFiles = files.filter((file) => extname(file.path) === '.md');
const cFamilyFiles = implementationFiles.filter((file) => ['.c', '.h', '.cpp', '.hpp'].includes(extname(file.path)));
const typescriptFiles = implementationFiles.filter((file) => ['.ts', '.tsx'].includes(extname(file.path)));
const referenceProgram = await readFile('reference-set/reference-set.binscript', 'utf8');

const facts = {
  methodology:
    'This page counts physical lines in source files. It leaves out dependencies, build output, dist, and generated reference images.',
  totals: {
    sourceLines: implementationFiles.reduce((total, file) => total + file.lines, 0),
    sourceFiles: implementationFiles.length,
    cFamilyLines: cFamilyFiles.reduce((total, file) => total + file.lines, 0),
    typescriptLines: typescriptFiles.reduce((total, file) => total + file.lines, 0),
    documentationLines: markdownFiles.reduce((total, file) => total + file.lines, 0),
    referenceProgramLines: lineCount(referenceProgram),
    referenceOutputs: 4312,
  },
  areas,
  semanticFiles: files
    .filter((file) => file.path.startsWith('lib/semantic/program_'))
    .map((file) => ({ path: file.path, lines: file.lines })),
} as const;

const unformatted = `/* Generated by scripts/project-facts.ts. Do not edit. */\nexport const projectFacts = ${JSON.stringify(facts, null, 2)} as const;\n`;
const formatted = await format(destination, unformatted, { printWidth: 140, singleQuote: true });
if (formatted.errors.length !== 0) throw new Error('The generated project facts could not be formatted.');
const generated = formatted.code;

if (checkOnly) {
  let current = '';
  try {
    current = await readFile(destination, 'utf8');
  } catch {}
  if (current !== generated) {
    console.error(`${destination} is stale. Run npm run project:facts.`);
    process.exitCode = 1;
  }
} else {
  await writeFile(destination, generated);
  console.log(`Wrote ${destination} from ${implementationFiles.length} source files.`);
}
