import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ReferenceManifest } from './reference-manifest.js';

const repositoryRoot = resolve(fileURLToPath(new URL('..', import.meta.url)));
const manifestPath = resolve(repositoryRoot, 'reference-set/reference-manifest.json');
const outputPath = resolve(repositoryRoot, 'reference-set/reference-set.binscript');
const contractPath = resolve(repositoryRoot, 'reference-set/reference-conformance.tsv');

const flatColors: Readonly<Record<string, string>> = {
  col_black_1: '#000000',
  col_black_2: '#808080',
  col_black_3: '#c0c0c0',
  col_black_4: '#ffffff',
  col_blue_lo: '#000080',
  col_blue_hi: '#0000ff',
  col_green_lo: '#008000',
  col_green_hi: '#00ff00',
  col_cyan_lo: '#008080',
  col_cyan_hi: '#00ffff',
  col_red_lo: '#800000',
  col_red_hi: '#ff0000',
  col_yellow_lo: '#808000',
  col_yellow_hi: '#ffff00',
  col_pink_lo: '#800080',
  col_pink_hi: '#ff00ff',
};

const recoveredBlueVariantExpressions: Readonly<Record<string, string>> = {
  grad00blk100: 'reference-blue-hi.over(reference-grad00-black)',
  grad00blk25: 'reference-blue-hi.over(reference-grad00-black, 25%)',
  grad00wht: 'reference-blue-hi.over(reference-grad00-white)',
  grad01blk100: 'reference-blue-hi.over(reference-grad01-black)',
  grad01blk25: 'reference-blue-hi.over(reference-grad01-black, 25%)',
  grad01wht: 'reference-blue-hi.over(reference-grad01-white)',
  grad02blk100: 'reference-blue-hi.over(reference-grad02-black)',
  grad02blk50: 'reference-blue-hi.over(reference-grad02-black, 50%)',
  grad02wht: 'reference-blue-hi.over(reference-grad02-white)',
  grad03blk100: 'reference-blue-hi.over(reference-grad03-black)',
  grad03blk25: 'reference-blue-hi.over(reference-grad03-black, 25%)',
  grad03blk50: 'reference-blue-hi.over(reference-grad03-black, 50%)',
  grad03wht100: 'reference-blue-hi.over(reference-grad03-white)',
  grad04blk100: 'reference-blue-hi.over(reference-grad04-black)',
  grad04blk50: 'reference-blue-hi.over(reference-grad04-black, 50%)',
  grad04wht: 'reference-blue-hi.over(reference-grad04-white)',
};

function referenceExpression(file: ReferenceManifest['files'][number], knownPaths: ReadonlySet<string>): string {
  if (file.family === 'flat-color') {
    const name = file.path.slice(file.path.lastIndexOf('/') + 1, -'.png'.length);
    const color = flatColors[name];
    if (color === undefined) throw new Error(`Missing analytic flat color for ${file.path}.`);
    return `artifact(${JSON.stringify(file.path)}, fill(${color}).size(64))`;
  }
  if (file.family === 'gradient-masks') {
    const match = /\/(\d\d)\.png$/.exec(file.path);
    const index = match === null ? Number.NaN : Number(match[1]);
    if (Number.isInteger(index) && index >= 0 && index < 18) {
      return `artifact(${JSON.stringify(file.path)}, reference-alpha-map(${index}))`;
    }
  }
  if (file.family === 'gradient-variants') {
    const match = /^col bin 2\/rgb\/col_blue_hi-(grad0[0-4][^.]+)\.png$/.exec(file.path);
    const expression = match === null ? undefined : recoveredBlueVariantExpressions[match[1]];
    if (expression !== undefined) return `artifact(${JSON.stringify(file.path)}, ${expression})`;
  }
  if (file.family === 'downscaled') {
    const basename = file.path.slice('blue 64-8 24 bit/'.length);
    const upstream = `col bin 2/rgb/${basename}`;
    if (knownPaths.has(upstream)) {
      return `artifact(${JSON.stringify(file.path)}, asset(${JSON.stringify(upstream)}, width: 64, height: 64).size(8))`;
    }
  }
  return `asset(${JSON.stringify(file.path)}, width: ${file.width}, height: ${file.height})`;
}

function maxChannelError(file: ReferenceManifest['files'][number]): number {
  if (file.equivalence !== 'bounded-difference') return 0;
  if (/^col bin 2\/rgb\/col_blue_hi-grad0[0-4][^.]+\.png$/.test(file.path)) {
    if (file.path.includes('blk25')) return 4;
    if (file.path.includes('blk50')) return 7;
    return 13;
  }
  if (file.family === 'downscaled') {
    return file.path.endsWith('-grad14wht.png') || file.path.endsWith('-grad16wht.png') ? 2 : 1;
  }
  throw new Error(`Missing bounded-difference tolerance for ${file.path}.`);
}

function provenance(file: ReferenceManifest['files'][number], expression: string): string {
  if (file.equivalence === 'byte-alias') return 'byte-alias';
  if (file.equivalence === 'pixel-alias') return 'pixel-alias';
  if (expression.startsWith('asset(')) return 'raster-asset';
  return expression.includes('asset(') ? 'analytic-from-asset' : 'analytic';
}

export function generateReferenceBinScript(manifest: ReferenceManifest): string {
  const knownPaths = new Set(manifest.files.map((file) => file.path));
  const lines = [
    '// Generated by scripts/reference-binscript.ts from reference-set/reference-manifest.json.',
    '// Recovered flat colors, alpha maps 00-17, the blue grad00-grad04 slice, and 80 downscales are analytic.',
    '// Other compatibility behavior stays explicit as encoded assets.',
    'import "binblock/basic"',
    'import "binblock/reference-set"',
    '',
    'reference-blue-hi := fill(#0000ff).size(64)',
    'reference-grad00-black := rg(black 64%, transparent-black, center: [31.5, 31.5], radius: 32, easing: "legacy")',
    'reference-grad01-black := rg(transparent-black 32%, black, center: [31.5, 31.5], radius: 32, easing: "legacy")',
    'reference-grad02-black := rg(black 32%, transparent-black, center: [31.5, 31.5], radius: 32, easing: "legacy")',
    'reference-grad03-black := rg(transparent-black, black, center: [31.5, 31.5], radius: 32, easing: "legacy")',
    'reference-grad04-black := rg(black, transparent-black, center: [31.5, 31.5], radius: 32, easing: "legacy")',
    'reference-grad00-white := reference-grad00-black.rgb(white)',
    'reference-grad01-white := reference-grad01-black.rgb(white)',
    'reference-grad02-white := reference-grad02-black.rgb(white)',
    'reference-grad03-white := reference-grad03-black.rgb(white)',
    'reference-grad04-white := reference-grad04-black.rgb(white)',
    '',
  ];
  for (const family of manifest.families) {
    const files = manifest.files.filter((file) => file.family === family.id);
    lines.push(`${family.id} := collect([`);
    for (const file of files) {
      lines.push(`  ${referenceExpression(file, knownPaths)}, // sha256:${file.encodedSha256} ${file.equivalence}`);
    }
    lines.push('])', '');
  }
  lines.push('default := union(', ...manifest.families.map((family) => `  ${family.id},`), ')', 'default', '');
  return lines.join('\n');
}

export function generateReferenceContracts(manifest: ReferenceManifest): string {
  const orderedFiles = manifest.families.flatMap((family) => manifest.files.filter((file) => file.family === family.id));
  const knownPaths = new Set(manifest.files.map((file) => file.path));
  return [
    '# index\tpath\tequivalence\tmax-channel-error\tprovenance\tdecoded-rgba8-sha256\tencoded-sha256\talias-identity\talias-target',
    ...orderedFiles.map((file, index) => {
      const expression = referenceExpression(file, knownPaths);
      return [
        index,
        file.path,
        file.equivalence,
        maxChannelError(file),
        provenance(file, expression),
        file.decodedRgba8Sha256,
        file.encodedSha256,
        file.alias?.identity ?? '',
        file.alias?.target ?? '',
      ].join('\t');
    }),
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8')) as ReferenceManifest;
  const generated = generateReferenceBinScript(manifest);
  const contracts = generateReferenceContracts(manifest);
  if (process.argv.includes('--check')) {
    const existing = await readFile(outputPath, 'utf8').catch(() => '');
    if (existing !== generated) throw new Error('reference-set/reference-set.binscript is stale; run npm run reference:program.');
    const existingContracts = await readFile(contractPath, 'utf8').catch(() => '');
    if (existingContracts !== contracts)
      throw new Error('reference-set/reference-conformance.tsv is stale; run npm run reference:program.');
    return;
  }
  await Promise.all([writeFile(outputPath, generated), writeFile(contractPath, contracts)]);
}

await main();
